
// Code generated by MockGen. DO NOT EDIT.
// Source: ml.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gocv "gocv.io/x/gocv"
)

// MockNeuralNet is a mock of NeuralNet interface.
type MockNeuralNet struct {
	ctrl     *gomock.Controller
	recorder *MockNeuralNetMockRecorder
}

// MockNeuralNetMockRecorder is the mock recorder for MockNeuralNet.
type MockNeuralNetMockRecorder struct {
	mock *MockNeuralNet
}

// NewMockNeuralNet creates a new mock instance.
func NewMockNeuralNet(ctrl *gomock.Controller) *MockNeuralNet {
	mock := &MockNeuralNet{ctrl: ctrl}
	mock.recorder = &MockNeuralNetMockRecorder{mock}
	return mock
}