// Code generated by MockGen. DO NOT EDIT.
// Source: yolov5.go

// Package mock_yolov5 is a generated GoMock package.
package mock_yolov5

import (
        reflect "reflect"

        gomock "github.com/golang/mock/gomock"
        yolov5 "github.com/wimspaargaren/yolov5"